### ISSUE TITLE
The course titles should link to results (if present) in "my courses" section.

### ISSUE THREAD

**Issue by Steditor** [fsr-itse/EvaP#1023]
I would like to see the behavior unified: As it is in the "results" section, all course titles should link to the results (if present).
Currently there are three different versions:
 - for contributers, there is a small icon-button
 - for participants, there is a bigger text-button
 - in the "results" section, the title is the link

Or is this covered in #571?

**Comment by karyon** [comment]
heh, @janno42 actually did this on monday@ https://github.com/fsr-itse/EvaP/commit/bcceee90243b5a2523f2eef149040c7a245feea1 :) but he left the buttons as they are, maybe even more unification makes sense?

**Comment by Steditor** [comment]
I see - thx! I only looked for an issue, not for a commit message :wink:

I would like to see unified buttons, I'm not sure if removing would be a good choice, as (in contrast to the results page) the titles themselves are not "obviously" pointing to the results.

**Comment by janno42** [comment]
removing is a bad idea, because it doesn't make sense that some options are available as buttons while others are not. using the same buttons all over is a possibility but currently doesn't fit to the way the buttons are used (icons vs text because of different amounts of available space). in general, the number of users who have both rolls is quite small - optimizing for them doesn't seem to be necessary, although if it's easy enough it would of course make sense. i have several ideas for possible changes on the index pages, but i'm not yet sure about all the details. this should probably become a broader ticket related to the overall index page experience or so.

**Comment by Steditor** [comment]
Then this issue is obviously already solved with #1021. Thank you!

**Comment by karyon** [comment]
thanks for reporting!
