### ISSUE TITLE
Fix jumping page when opening modals

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#1106]
When opening a modal the page jumps a bit because `padding-right` is added to the body and navbar. This should not happen.

**Comment by pixunil** [comment]
I am suspecting that ce1b6350e2883870e95d9760708984d087b4b358 adds to the problem. As default, bootstrap removes the scrollbar with `overflow: hidden` (to get a cleaner design; who knows?) and adds the `padding-right` to fill the space the missing bar is leaving behind. Now, with the scrollbar, the padding is misplaced.
Removing the stated line does help, but I am experiencing also a slightly jump in the background pattern, which is caused by `background-attachment: fixed`
