### ISSUE TITLE
Midterm evaluation message

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#1176]
Courses should get an option to be marked as midterm evaluations. For these courses on the student voting page a message will be shown to explain that the evaluation results will be published while the course is still running and before its exam grades are published.

**Comment by karyon** [comment]
is this really necessary? i mean there is probably some communication going on so students know what's happening, and whoever communicates with them can simply tell them that, can't they? also, i think it's kinda obvious that we're not holding back these results for several months...

basically, i'd rather not have workarounds because we don't have #1047 yet.

**Comment by janno42** [comment]
yes, this is absolutely necessary, an explicit fsr decision and we need it before the next midterm evaluations take place. #1047 might take a while - this can be part of it then.

**Comment by karyon** [comment]
could you share some of the reasoning?

**Comment by janno42** [comment]
we're also using midterm evaluations for courses which span over multiple semesters. we received complaints about not informing the students on the page that the results would be published before the course ends.

**Comment by karyon** [comment]
alright, thanks.
