### ISSUE TITLE
Implement results data retention policy

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#1194]
The results index page should only show the current plus the last 6 semesters, with no option to show older ones.

People should still be able to access "their" courses for an indefinite time span. Therefore, courses from "hidden" semesters that the user participated in or contributed to are still included in the course index page.

Access to individual course pages should be restricted accordingly. Staff users (not reviewers) should be able to access all courses indefinitely, although the results index looks the same for them and they have to use the staff pages to access individual courses.

The student index, contributor index, and staff pages probably need no change at all.

Rationale: We just don't see any practical reason to access courses older than that for most people. However, restricting access to one's own courses seemed overly restrictive. Staff users should still be able to access older, individual courses for the purpose of analyzing the evaluation results e.g. for a specific lecture over time or a specific contributor. For this, accessing individual courses via the staff pages is sufficient, so there is no need to give staff users additional rights on the result index page.

**Comment by janno42** [comment]
We discussed that there is no real need for students to access course results from courses in semesters older than the last six (plus current). Contributors need older data only for their own courses and can view them from their individual index pages. This allows for a universal results index page which displays only the courses from the last six semesters for all users, making it a consistent view for all users which can also be loaded very fast.

- A semester attribute `results_available` (or similar) should be introduced that can manually be changed via the UI by staff users.
  - If `True`, the courses of this semester will be included on the results index page and the results are linked on contributors' and students' index pages.
  - If `False`, the courses of this semester will not be visible on the results index page, no links from the student's index pages will be shown and students no longer can access the courses' results pages. Contributors can still see the distribution and average grade on their results page and will still have a link to the courses' results pages. Staff users will also still be able to access the courses' results pages from the semester management pages.
- The contributor index page should be changed so that users can filter and search on the page similar to the new results index page from #1149.
