### ISSUE TITLE
Navbar cache refresh is broken

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#1208]
Since e0beea96a39419422a6c20621f07ba15aa288e1a the navbar cache is based on `session.session_key` but the refresh operation in `delete_navbar_cache_for_users` in `staff/tools.py` tries to delete a key based on `user.username`.

Since this is not working correctly for quite some time now we definitely need to have a test for that as well.

**Comment by He3lixxx** [comment]
We changed the cache to use the session key because we had problems with cached csrf tokens in the navbar. Since we don't have forms in the navbar anymore, we could just return to using the username as cache key.

Keeping the session id is not that easy, since we'd still have to be able to delete all navbar cache entries for a list of users, but if the session id is used as cache key, we have no way to finding all cache entries that are valid for a given user.

Thus, I will change this back so it uses the username again, and add tests for it.
