### ISSUE TITLE
Bulk import participants to a course

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#248]
There should be an option for student representatives to add a list of external students to a course without having to first create each user individually.

This will be needed for D-School courses where the student representatives will get a list of participants (names and email addresses) of external students who are not part of the initial enrolment data.

The bulk import should create the given users (if they don't exist yet) and add them to a specified course.

**Comment by schumannd** [comment]
djangos update_or_create() should take care of this problem. If no username is given, we need a mechanism to create one for new users. Does this already happen? Further tests are necessary with bigger test files

**Comment by karyon** [comment]
the question was whether an import overwrites enrolments or adds them, and i think the answer was that neither happens because the importer right now does not touch existing courses at all.

regarding external usernames, there is importer.generate_external_usernames_if_external, you might want to check that out.
