### ISSUE TITLE
Method process_response of class Django403Middleware is not neccessary

### ISSUE THREAD

**Issue by homoroselaps** [fsr-itse/EvaP#488]
The Method process_response of class Django403Middleware is called when ever a response is made, but 403 error pages get created with an empty methode any way.

**Comment by karyon** [comment]
our custom 403 was implemented with django 1.3. since 1.4, django by default searches for 403.html in the root template directory and displays that when a 403 is raised. removing the code in this method made django do its default behaviour, which was the same as our custom one.

so i could just remove all that custom crap (00502d393a)! thanks for making me look into this :)
