### ISSUE TITLE
Results UI rework

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#571]
this is a placeholder and reminder for the results UI rework.

(there is an etherpad for that)

**Comment by janno42** [comment]
The idea is to have one page containing all the information (all courses, all degrees, all semesters) in one large table. This table can then be filtered by selecting one or multiple filter checkboxes (e.g. only courses from the last 4 semesters in Bachelor degree) and by the already existing text box (e.g. only courses by a certain responsible).

Because this list will be quite long, only the last N semesters could be initially selected. The results list needs to be cached to be loaded fastly.

Filter settings should be kept when opening the page again.

**Comment by janno42** [comment]
implemented in #1149
🎉 🎆
