### ISSUE TITLE
Vagrant permissions problem

### ISSUE THREAD

**Issue by balsagoth** [fsr-itse/EvaP#669]
When using Vagrant, i have to change the apache user and group to vagrant.
Apache needs to have write permissions on some folders like `/vagrant/evap/static_collected` and `/vagrant/evap/logs/evap.log`

Do you want a pull request to fix it?

**Comment by karyon** [comment]
i suppose you are on linux? because i think on windows this does not happen, possibly because the file permissions inside the shared folder differ. for me, inside the vm, the evap.log has the permissions 777.

so yeah, a pull request would be nice, as i don't have a linux machine and can't test this easily. whatever your solution is, please do a ``vagrant destroy && vagrant up`` to test it :)

**Comment by balsagoth** [comment]
No, I'm on OSX. I could try from the scratch again, and if it happens, i will provide a pull request.
What are the permissions and user of the folder `/vagrant/evap/static_collected` on your machine?

**Comment by karyon** [comment]
yeah, i should've said unix, what i meant is that maybe the access rights on files are mapped 1:1 between host and guest on unix hosts, and e.g. just set to 777 for the guest on windows hosts.

everything in static_collected is 777 for me as well.

**Comment by karyon** [comment]
@balsagoth may i ask how you found EvaP and why you were checking it out? you're not from HPI right?
