### ISSUE TITLE
Pagination for User view

### ISSUE THREAD

**Issue by schumannd** [fsr-itse/EvaP#755]
The view takes several seconds to load. We might need a pagination for the future feedback view as well.

**Comment by janno42** [comment]
We decided against pagination in the past. I think it was mainly because searching then gets more complicated than with the current sorttable.
On the other hand a faster loading user page is not too bad :)

**Comment by karyon** [comment]
besides the performance problem, whats the use case for pages? i.e. when would a staff user want to go to the next, previous, or a specific page in the user list?

regarding the performance problem, i had another look at it and the page needed a linear number of db queries again which slipped through the tests. having fixed that, the loading time went down from 5s to 3.6s with the test data (1350 users) on my machine (sandy brigde i3). which is better but still slow of course.

before paginating the table i'd rather just defer loading it, possibly decreasing overall loading time (because the request for the table data would be sent after the initial page is loaded) but at least the page loads fast intitially, or loading it in chunks. just having a search field that's processed on the server would have the disadvantage that you cannot search e.g. for the labels without lots of additional code (same goes for pagination btw)

so i'd
1. first look whether we can speed up rendering the template further
2. if that's really not enough, do deferred loading or some other idea if you have one
3. not do pagination unless you give me examples how the pagination ui widget might actually be used

random thought: we could send the data as json and render it client-side, but we would need to somehow (possibly inside the view or a django template) create a html template for a line of the table for that where the js code can insert the data.

**Comment by karyon** [comment]
of those 3.6s, 600ms are for the edit button and 600ms for the delete button. if i empty the for loop it still takes 2s, so there is really not that much to optimize anymore since it's just django's template engine that is slow as far as i can see.

**Comment by karyon** [comment]
update, the 2s are the big fat query, not the loop. the database itself needs only 100 or 200ms, what takes time is probably putting all the prefetched data (for each userprofile each course participated in and contributed to...) into python objects.

it should be possible to shortcut that for is_contributor by some more annotations, since we only need the existence of such courses. for can_staff_delete, this would be harder and probably infeasible. it might be better to e.g. always enable the delete button and when clicking it, checking can_staff_delete via ajax before showing the modal.

**Comment by karyon** [comment]
so. for future reference, here's a breakdown what happens on the user page.

1350 users. the view needs 2s to return. the query-count fix is already included.
* 0.3s for the contributions prefetch, needed for is_contributor and is_responsible labels.
* 0.6s for the courses_participating_in prefetch, needed for delete button.
* 0.25s for rendering the delete button.
* 0.3s for rendering the edit button, most of it is generating the url.
* 0.25s for rendering all the labels (7 total).

i see the following options:
* i could replace the contributions prefetch (0.3s) by four annotations.
* i could replace the courses_participating_in prefetch (0.6s) by two annotations which would replicate parts of can_staff_delete.
* we could defer disabling the delete button (in total 0.85s), that would require some ajax work. don't know how ugly the interactions with the modal would look like in the code.
* defer loading the table to make the page appear quicker
* load the table in chunks.
* do nothing.

i'd say we do nothing but it's up to @janno42 to decide whether it's too annoying right now or not.
