### ISSUE TITLE
Copy participants from other course

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#824]
It should be possible to not only import participants to a course from an excel sheet, but also to copy the participants from another course.

**Comment by karyon** [comment]
what's the use case for this?

**Comment by janno42** [comment]
e.g. courses for participants in bachelor projects. they participate in multiple preparation seminars that are not part of the enrollment data. after manually adding them all to one course it would be nice to just be able to copy them instead of adding them one by one again.

**Comment by janno42** [comment]
Actually, copying a whole course would probably be even better.

**Comment by He3lixxx** [comment]
I think this commit (#881) introduces another problem since the UserImportForm is used in two places:
- user import (/staff/user/import)
- course participant import (e.g. staff/semester/18/course/1603/participant_import).

With the current changes, the course selection is also shown when you want to import users which I don't understand.

Also, the idea of having the import-from-another-course functionality in the same form as the import-from-excel-file functionality makes the interface more confusing when implementing the 2-stage file import mechanism as discussed on Issue #678. I'd suggest leaving it on the same page but somehow making a distinction by putting them in two seperate areas that are completely independent on eachother.

**Comment by karyon** [comment]
> With the current changes, the course selection is also shown when you want to import users which I don't understand.
That's a bit weird indeed...

If you separate these parts, it might make sense to put the import-from-course into a separate form, which is displayed on the one page, but not on the other.
