### ISSUE TITLE
allow students to say that and why they have cancelled a course 

### ISSUE THREAD

**Issue by Nef10** [fsr-itse/EvaP#831]

**Comment by karyon** [comment]
multiple different solutions we discussed: 
1. don't do it because it's not important enough
2. add a regular text question to e.g. to the "other" questionnare for courses that asks something like "If you cancelled the course, why?"
3. do 2. plus add a yes/no question "have you cancelled the course" (ref #345). advantage would be to have a definitive answer to the question "how many people have quit the course". with out the yes/no question, people who quit may still leave the text question empty.
4. In the student index page, per course add a button "I quit this course". This opens a new page that asks for reasons for quitting and whether the person still wants to evaluate the course. The reason for that is that the person participated in most of the course and quit late, so they still might want to evaluate the course. If they choose to not evaluate the course, they are removed from the participant list, but only after a staff member verified that the person actually quit to prevent abuse to get rewards.

we opted for 2. since it requires almost no work and still lets us see how many people potentially might benefit from a more advanced solution.

since 2. requires no code changes, closing.
