### ISSUE TITLE
Update example files

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#929]
The example files must be updated so that they can be imported without errors.

**Comment by karyon** [comment]
i thought we had tests for that. if not, this issue includes writing tests for that :)

**Comment by He3lixxx** [comment]
The tests for the sample files are in evap/evaluation/tests/test_misc.py, testing the semester and user import sample files. I guess they pass due to the overrided settings, but I didn't look into that. These tests should be moved to staff/tests/test_views.py I guess.

The course person import sample file is not tested. Currently it's the same as the user import file, so the file is actually checked, but in case it changes, this might lead to missing tests.

**Comment by He3lixxx** [comment]
Assign please

I currently plan on doing it by opening a template sample file with xlrd, copying it to a xlwt workbook, modifying that so that the emails are correct and then serving the file in the HTTP response. This would happen in a new view (which will not be visible). The code will be less than 50 lines. Testing would happen in two layers:
1. Test that the template files are valid
2. Test that the substitution works

I think this would be the most efficient way.
