### ISSUE TITLE
Error highlighting in course forms is broken

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#963]
When editing a course and changing e.g. the name to an already existing one, the form returns with an error but only displays a generic "was not saved, please resolve errors below", but the actual name field is rendered in green and does not show an error.
This must be fixed for all forms.

**Comment by He3lixxx** [comment]
Django's Form validation fails because the unique_together constraint of the Courses "name_de" or "name_en" fields together with the "semester" field is violated in that case. Since two fields are involved, Django does not assign this error to one of the fields. We don't render the non_field_errors, the error is not shown anywhere on the form. It would be nice to have the error assigned to the name_xy field involved since the semester field is not visible on the Form.
