### ISSUE TITLE
Responsible reminder email

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#980]
It should be possible to send a reminder email to a responsible person by clicking on a button in the todo list.
An (editable) email template repeating the most important information from the Editor Review Notice should be provided and the list of due courses should be accessible in this template.

**Comment by karyon** [comment]
following plan:

* each user in the todo list gets a button `Send reminder` which opens an email form
* The form has a disabled `To` field containing the person corresponding to the button
* The form has a disabled `Cc` field containing delegates and cc users of that user
* subject and body are filled from the template. 
  * bonus: render that template and use the rendered text as initial data

the `To` and `Cc` fields should not be editable, because that quickly becomes complex. since we want the cc recipients to be shown, editing the `To` field would require us to load delegates and cc users via ajax. additionally editing cc recipients would make things even worse.
